name: Run Python Script

# 定时触发器，每天凌晨0点运行 (UTC时间)
on:
  schedule:
    - cron: '*/10 * * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    
    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    # 安装依赖（如果有）
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip requests
        # 如果有 requirements.txt，可以添加：
        # pip install -r requirements.txt
        
    # 运行 Python 脚本
    - name: Run script
      run: python proxy/gen_share_links.py
      
    # 提交结果文件
    - name: Commit results
      run: |
        git config --local user.email "kanayuki@163.com"
        git config --local user.name "kanayuki"
        git add share_links.txt
        git commit -m "Update share_links.txt with latest results" || echo "No changes to commit"
        git push